### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by simonszhu** [AngeLouCN/Min_Max_Similarity#1]
Thank you for your listening! May i ask you the url of all these datasets or share the datasets by some ways? Due to that for the first dataset i can not open the URL, for the second dataset, i can not get the dataset from the website, for the third dataset, i also can not open the URL.

truely thanks!

**Comment by AngeLouCN** [comment]
Hi, here is the link for Kvasir-instrument: https://datasets.simula.no/kvasir-instrument/
and here is the link for EndoVis'17: https://endovissub2017-roboticinstrumentsegmentation.grand-challenge.org/
and we still do not release the third dataset.

**Comment by simonszhu** [comment]
thank you for your help!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "AngeLouCN/Min_Max_Similarity"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月2日(星期一) 中午12:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [AngeLouCN/Min_Max_Similarity] dataset (Issue #1)





 
Hi, here is the link for Kvasir-instrument: https://datasets.simula.no/kvasir-instrument/
 and here is the link for EndoVis'17: https://endovissub2017-roboticinstrumentsegmentation.grand-challenge.org/
 and we still do not release the third dataset.
